# Generated by Django 5.0.2 on 2024-02-15 17:40

from django.db import migrations, models
import pandas


def import_all_products(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Product = apps.get_model("warehouse", "Product")
    db_alias = schema_editor.connection.alias
    list_of_products = []
    dataframe = pandas.read_excel('C:\\Users\\mariu\\PycharmProjects\\tekwillV4Django\\date.xlsx')
    for index, row in dataframe.iterrows():
        code = row['Nr.articol']
        quantityt = row['SI cantitate']
        name = row['Descriere']
        list_of_products.append(
            Product(
                name=name,
                quantity=quantityt,
                code=code
            )
        )
    Product.objects.using(db_alias).bulk_create(
        list_of_products
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RunPython(import_all_products)
    ]
