# Generated by Django 5.0.2 on 2024-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0002_alter_conversionhistory_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=5)),
                ('to_currency', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=32)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
